name: dart_mars
description: A sample command-line application.
version: 1.0.3
homepage: https://github.com/tangpanqing/dart_mars

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  process_run: ^0.12.1
  yaml: ^3.1.0
  mysql1: ^0.19.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
